# Generated by Django 5.1.4 on 2024-12-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("symbol", models.CharField(max_length=10)),
                ("net_position", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
            ],
        ),
    ]
