# Generated by Django 5.1.4 on 2024-12-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Trade",
            new_name="Transaction",
        ),
        migrations.AlterModelTable(
            name="transaction",
            table="trading_transactions",
        ),
    ]
