# Generated by Django 5.1.4 on 2024-12-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_rename_trade_transaction_alter_transaction_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Position",
        ),
    ]
