# Generated by Django 5.1.4 on 2024-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_delete_position"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["symbol"], name="trading_tra_symbol_e8b80a_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["symbol", "date"], name="trading_tra_symbol_df2bab_idx"
            ),
        ),
    ]
