# Generated by Django 5.1.4 on 2024-12-14 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_alter_transaction_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 14, 19, 52, 52, 607150, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
