# Generated by Django 5.1.4 on 2024-12-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0008_alter_transaction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNetPosition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(db_index=True, max_length=10)),
                ("net_position", models.FloatField()),
                ("date", models.DateField()),
            ],
            options={
                "db_table": "trading_daily_net_positions",
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="trading_dai_symbol_982e29_idx"
                    ),
                    models.Index(
                        fields=["symbol", "date"], name="trading_dai_symbol_2c7097_idx"
                    ),
                ],
            },
        ),
    ]
