name: "trading_webapp"
services:
  trading_backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    volumes:
      - ../src:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-your_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


networks:
  trading_app:
    driver: bridge